version: '3.8'
services:
  db:
    image: postgres:13
    container_name: langapp_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2-alpine
    container_name: langapp_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: